---
title: "ALIGNMENT_CONTRAST_IN_HUIYANG_HAKKA_FALLING_TONES"
collection: publications
permalink: /publication/ALIGNMENT_CONTRAST_IN_HUIYANG_HAKKA_FALLING_TONES
excerpt: 'The aim of this paper is to examine the role of tonal alignment in the perception and production of two falling tones in Huiyang Hakka. Whether tonal alignment can be contrastive in contour tones within a language is a longstanding debate in tonal typology. Previous research indicates that tonal alignment can differ systematically in production; however, the question of whether tonal alignment can be (phonologically) contrastive in contour tones is still unresolved. In this study, we explored whether tonal alignment is contrastive in both production and perception of falling tones. The results of a production experiment show that the two falling tones in Huiyang Hakka have a significant difference in tonal alignment; however, tone duration also differs consis tently between the two falling tones. To find out more about the perceptual relevance of these correlates, I conducted a perception experiment to test which phonetic param eter(s) is/are the major correlate that native speakers use to encode the tonal contrast between their falling tones. The results indicate that tonal alignment is perceptually contrastive in Huiyang Hakka falling tones, providing experimental evidence of both production and perceptual relevance of alignment contrasts.'
date: 2022-01-01
venue: "The 96th Annual Meeting of the Linguistic Society of America"
paperurl: 'https://www.researchgate.net/publication/371938607_ALIGNMENT_CONTRAST_IN_HUIYANG_HAKKA_FALLING_TONES'
citation: 'Chen, Jingyi. (2022). ALIGNMENT CONTRAST IN HUIYANG HAKKA FALLING TONES. '
---
The aim of this paper is to examine the role of tonal alignment in the perception and production of two falling tones in Huiyang Hakka. Whether tonal alignment can be contrastive in contour tones within a language is a longstanding debate in tonal typology. Previous research indicates that tonal alignment can differ systematically in production; however, the question of whether tonal alignment can be (phonologically) contrastive in contour tones is still unresolved. In this study, we explored whether tonal alignment is contrastive in both production and perception of falling tones. The results of a production experiment show that the two falling tones in Huiyang Hakka have a significant difference in tonal alignment; however, tone duration also differs consis tently between the two falling tones. To find out more about the perceptual relevance of these correlates, I conducted a perception experiment to test which phonetic param eter(s) is/are the major correlate that native speakers use to encode the tonal contrast between their falling tones. The results indicate that tonal alignment is perceptually contrastive in Huiyang Hakka falling tones, providing experimental evidence of both production and perceptual relevance of alignment contrasts..

[Download paper here](https://www.researchgate.net/publication/371938607_ALIGNMENT_CONTRAST_IN_HUIYANG_HAKKA_FALLING_TONES)

Recommended citation: Chen, Jingyi. (2022). ALIGNMENT CONTRAST IN HUIYANG HAKKA FALLING TONES.
